FROM node:14-alpine as base

WORKDIR /usr/src/app

COPY rollup.config.js ./
COPY svelte.config.js ./
COPY package*.json ./

RUN npm install

COPY ./src ./src
COPY ./public ./public

FROM base as dev
EXPOSE 5000 35729
ENV HOST=0.0.0.0
CMD [ "npm", "run", "dev" ]

FROM base as prod
CMD ["npm", "run-script", "build"]