version: '3.8'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '4001:3000'
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - .dev.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
      target: dev
    ports:
      - '5000:5000'
      - '35729:35729'
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - flask

  db:
    image: 'postgres:13'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=snakes
      - POSTGRES_DB=flask-app

volumes:
  postgres_data:
